### ISSUE TITLE
Need to consolidate test results into a single table

### ISSUE THREAD

**Issue by henryhund** [analyst-collective/analytics#17]
We should consolidate tests into a single table. Right now, we have many stub views created for each set of transformations/analyses. We should create a single test table, if it doesn't exist, and append or replace results from each of the tests, resulting in a central place where test results can be reviewed.

**Comment by jthandy** [comment]
This is more likely to happen in dbt. Currently, the runner doesn't actually run tests, but we need to modify it so that it does.
